/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_luozhanming_opengldemo_JniTest */

#ifndef _Included_cn_luozhanming_opengldemo_JniTest
#define _Included_cn_luozhanming_opengldemo_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_luozhanming_opengldemo_JniTest
 * Method:    jniString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_luozhanming_opengldemo_FFmpgeTest_jniString
  (JNIEnv *, jobject);

JNIEXPORT jint JNICALL Java_cn_luozhanming_opengldemo_FFmpgeTest_decode(JNIEnv *, jobject,jstring,jstring);



#ifdef __cplusplus
}
#endif
#endif
